# NOTE: update this with your service name
service: serverless-starter

# Create an optimized package for our functions 
# package:
#   individually: true

plugins:
  # - serverless-domain-manager
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs10.x
  # stage: dev
  stage: prod
  # memorySize: 2048 # recommended
  profile: NesinTechnologies
  region: ap-south-1
  lambdaHashingVersion: 20201221
  # To load environment variables externally
  # rename env.example to .env and uncomment
  # the following line. Also, make sure to not
  # commit your .env.
  #
  #environment:
  #  SAMPLE_ENV_VAR: ${env:SAMPLE_ENV_VAR}
custom:
  serverless-offline:
    port: 7777
  bundle:
    linting: false
  # customDomain:
  #   domainName: hello.hugethoughts.com
  #   basePath: ''
  #   stage: ${self:provider.stage}
  #   createRoute53Record: false
functions:
  app:
    handler: lambda.handler 
    events: 
      - http:
          method: ANY   
          path: /{proxy+}
          cors: true